server:
  port: "8000"

database:
  url: "postgres://iflab:Tischfussball@192.168.178.67:5432/ripe"

plugin:
  dir: "./target/debug"

mqtt:
  brokers:
    - internal:
        uri: "tcp://broker.hivemq.com:1883"
      external:
        uri: "wss://broker.hivemq.com:8884/mqtt"

  timeout_ms: 2500
  log_count: 50
  send_retries: 5
