server:
  port: "8000"

database:
  url: "postgres://localhost:localhost@localhost:5432/postgres"

plugin:
  dir: "/Users/knukro/Coding/priv/RIPE/backend/target/debug"

mqtt:
  client_id: "master-dev"
  timeout_ms: 5000
  log_count: 124
  send_retries: 8

  brokers:
    - internal:
        connection:
          scheme: "wss"
          host: "wss01.knukro.com"
          port: 443
      external:
        connections:
          - scheme: "wss"
            host: "wss01.knukro.com"
            port: 443
