server:
  port: "8000"

database:
  url: "postgres://localhost:localhost@localhost:5432/postgres"

plugin:
  dir: "./target/debug"

mqtt:
  client_id: "master-dev"
  timeout_ms: 5000
  log_count: 124
  send_retries: 8

  brokers:
    - internal:
        connection:
          scheme: "tcp"
          host: "broker.hivemq.com"
          port: 1883
      external:
        connections:
          - scheme: "tcp"
            host: "broker.hivemq.com"
            port: 1883
          - scheme: "wss"
            host: "broker.hivemq.com"
            port: 8884
