version: "3"
services:
  db:
    restart: "always"
    image: postgres:13-alpine
    ports:
      - 54321:5432
    #volumes:
    #- /data/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ripe
      POSTGRES_USER: iflab
      POSTGRES_PASSWORD: Tischfussball

  ripe:
    restart: "always"
    image: docker-registry.if-lab.de/arme/iftem_backend:latest
    environment:
      DATABASE_URL: postgres://iflab:Tischfussball@db:5432/ripe
      SERVER_PORT: 8080
      MQTT_BROKERS: tcp://127.0.0.1:1883,tcp://18.196.113.35:1883
    volumes:
      - ./plugins:/plugins
    ports:
      - 8080:8080    
