version: "2"
services:
  db:
    restart: "always"
    image: postgres:13-alpine
    ports: 
      - 54321:5432
    # volumes: ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: iftem
      POSTGRES_USER: iflab
      POSTGRES_PASSWORD: Tischfussball

  db_schema:
    restart: "no"
    image: clux/diesel-cli
    volumes:
      - "./:/volume"
    working_dir: "/volume"
    environment:
      DATABASE_URL: postgres://iflab:Tischfussball@db:5432/iftem
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 3 && diesel migration run"]

  threshold_plugin:
    image: docker-registry.if-lab.de/arme/iftem_backend/treshold_plugin:latest
    volumes:
      - ./plugins:/out

  backend:
    restart: "always"
    image: docker-registry.if-lab.de/arme/iftem_backend:latest
    environment:
      BIND_ADDR: 0.0.0.0:8000
      DATABASE_URL: postgres://iflab:Tischfussball@db:5432/iftem
      MQTT_URL: mqtt_broker
      MQTT_PORT: 1883
      MQTT_NAME: iftem-master
      PLUGIN_DIR: /plugins
    volumes:
      - ./plugins:/plugins
    ports:
      - 8000:8000
    depends_on:
      - db_schema
      - threshold_plugin
