FROM rust:1.45 as build

RUN mkdir /iftem && mkdir /out
WORKDIR /iftem

COPY ./core/ ./core

ARG theshold_agent

COPY ./plugins/treshold_agent ./plugins/treshold_agent

WORKDIR /iftem/plugins/treshold_agent
RUN cargo build --release

FROM rust:1.45
COPY --from=build /iftem/plugins/treshold_agent/target/release/treshold_agent.so .
ENTRYPOINT /bin/sh -c "cp /treshold_agent.so /out"
