version: "3"
services:
  db:
    restart: "always"
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ripe
      POSTGRES_USER: iflab
      POSTGRES_PASSWORD: Tischfussball
    networks:
      - default

  db_schema:
    restart: "no"
    image: clux/diesel-cli
    volumes:
      - ./:/volume
    working_dir: "/volume"
    environment:
      DATABASE_URL: postgres://iflab:Tischfussball@db:5432/ripe
    depends_on:
      - db
    entrypoint:
      [
        "sh",
        "-c",
        "while sleep 2; do $$(diesel migration run); if [ $$? -eq 0 ]; then echo 'Migration done' && exit 0; fi ; done",
      ]
    networks:
      - default

  backend:
    restart: "no"
    image: docker-registry.if-lab.de/arme/iftem_backend:latest
    depends_on:
      - db_schema
    networks:
      - default
      - proxy
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=PathPrefixStrip:/$CI_PROJECT_PATH_SLUG
        - traefik.port=8080
        - traefik.docker.network=proxy
        - traefik.http.middlewares.autodetect.contenttype.autodetect=false
    command: ["sh", "-c", "while :;do sleep 1 && /app/ripe; done"]

networks:
  default:
    external: false
  proxy:
    external: true
