version: "3"
services:
  db:
    image: postgres:13-alpine
    ports:
      - 54321:5432
    #volumes:
    #- /data/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ripe
      POSTGRES_USER: iflab
      POSTGRES_PASSWORD: Tischfussball

  ripe:
    build: .
    environment:
      DATABASE_URL: postgres://iflab:Tischfussball@db:5432/ripe
      SERVER_PORT: 8080
      MQTT_BROKER_TCP: tcp://knukro.com:1883
      MQTT_BROKER_WSS: wss://knukro.com:9001
      MQTT_LOG_COUNT: 20
      MQTT_SEND_RETRIES: 5
      MQTT_TIMEOUT_MS: 2500
    volumes:
      - ./plugins:/plugins
    ports:
      - 8080:8080    
