version: "2"
services:
  db:
    restart: "always"
    image: postgres:13-alpine
    ports:
      - 54321:5432
    environment:
      POSTGRES_DB: ripe
      POSTGRES_USER: iflab
      POSTGRES_PASSWORD: Tischfussball

  db_schema:
    restart: "no"
    image: clux/diesel-cli
    volumes:
      - "./:/volume"
    working_dir: "/volume"
    environment:
      DATABASE_URL: postgres://iflab:Tischfussball@db:5432/ripe
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 3 && diesel migration run"]

  ripe:
    restart: "always"
    image: ripe:latest
    environment:
      DATABASE_URL: postgres://iflab:Tischfussball@db:5432/ripe
      SERVER_PORT: 8080
      MQTT_NAME: iot-master
      MQTT_BROKERS: tcp://127.0.0.1:1883,tcp://18.196.113.35:1883
    volumes:
      - ./plugins:/plugins
    ports:
      - 8080:8080
    depends_on:
      - db_schema
