version: "3"
services:
  db:
    restart: "always"
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ripe
      POSTGRES_USER: iflab
      POSTGRES_PASSWORD: Tischfussball
    networks:
      - default

  backend:
    restart: "no"
    image: docker-registry.if-lab.de/arme/iftem_backend:latest
    networks:
      - default
      - proxy
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=PathPrefixStrip:/$CI_PROJECT_PATH_SLUG
        - traefik.port=8080
        - traefik.docker.network=proxy
        - traefik.http.middlewares.autodetect.contenttype.autodetect=false

networks:
  default:
    external: false
  proxy:
    external: true
