[package]
name = "iftem_core"
version = "0.1.0"
authors = ["Aron Metzig <aron.metzig@interface-ag.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "0.2", features = [ "sync", "rt-core", "time" ] }
slog = "2.5"

[build-dependencies]
rustc_version = "0.2.3"
