[package]
name = "ripe"
version = "0.1.0"
authors = ["Aron Metzig <aron.metzig@interface-ag.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# derived core dependencies
ripe_core = { path = "../core" }
chrono = { version = "*", features = ["serde"] }
serde = { version = "*", features = ["derive"] }
tokio = { version = "*", features = ["full"] }
utoipa = { version = "*", features = ["chrono"] }

# derived duplicate dependencies
futures-core = "*"
slog = "*" 
libloading = "*"
parking_lot = "*"
pin-project-lite = "*"
rand = "*"
chrono-tz = "*"

base64 = "0.21"
ctrlc = "3.2"
dotenv = "0.15"
env_logger = "0.10"
futures = "0.3"
notify = "5.0"
once_cell = "1.18"
serde_json = "1" 
sloggers = "2"
utoipa-swagger-ui = "3"
warp = "0.3"
wasmer = "3"
paho-mqtt = "0.12"

[target.'cfg(not(target_arch = "aarch64"))'.dependencies]
sqlx = { version = "0.6", features = [ "postgres", "macros", "migrate", "chrono", "runtime-tokio-native-tls" ] }

[target.'cfg(target_arch = "aarch64")'.dependencies]
sqlx = { version = "0.6", features = [ "postgres", "macros", "migrate", "chrono", "runtime-tokio-rustls" ] }
