[package]
name = "ripe"
version = "0.1.0"
authors = ["Aron Metzig <aron.metzig@interface-ag.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# derived core dependencies
ripe_core = { path = "../core" }
chrono = { version = "*", features = ["serde"] }
chrono-tz = "*"
serde = { version = "*", features = ["derive"] }
tokio = { version = "*", features = ["full"] }

# derived duplicate dependencies
futures-core = "*"
slog = "*" 
libloading = "*"
parking_lot = "*"
pin-project-lite = "*"
rand = "*"

base64 = "0.13"
ctrlc = "3.1"
dotenv = "0.15"
env_logger = "0.8"
futures = "0.3"
notify = "4.0"
once_cell = "1.7"
serde_json = "1" 
sloggers = "1"
sqlx = { version = "0.5", features = [ "postgres", "migrate", "chrono", "runtime-tokio-rustls" ] }
warp = "0.3"
wasmer = "2"

[target.x86_64-unknown-linux-gnu.dependencies]
paho-mqtt = { version = "0.9" }

[target.aarch64-unknown-linux-gnu.dependencies]
# paho-mqtt = { version = "0.9", features = ["vendored-ssl"] }
