[package]
name = "iftem"
version = "0.1.0"
authors = ["Aron Metzig <aron.metzig@interface-ag.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iftem_core = { path = "../core" }

base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
ctrlc = "3.1"
diesel = { version = "1.4", features = ["postgres", "chrono"] }
dotenv = "0.15"
env_logger = "0.8"
futures = "0.3"
libloading = "0.7"
notify = "4.0"
once_cell = "1.7"
parking_lot = { version = "0.11", features = ["send_guard"] } 
paho-mqtt = "0.9"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1" 
slog = "2.7" 
sloggers = "1"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
wasmer = "1"