[package]
name = "ripe"
version = "0.1.0"
authors = ["Aron Metzig <aron.metzig@interface-ag.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# derived core dependencies
ripe_core = { path = "../core" }
chrono = { version = "*", features = ["serde"] }
serde = { version = "*", features = ["derive"] }
tokio = { version = "*", features = ["full"] }
# derived duplicate dependencies
parking_lot = { version = "*", features = ["send_guard"] } 
slog = "*" 
libloading = "*"
futures-core = "*"
pin-project-lite = "*"

base64 = "0.13"
ctrlc = "3.1"
diesel = { version = "1.4", features = ["postgres", "chrono"] }
diesel_migrations = "*"
dotenv = "0.15"
env_logger = "0.8"
futures = "0.3"
notify = "4.0"
once_cell = "1.7"
paho-mqtt = "0.9"
rand = "0.8"
serde_json = "1" 
sloggers = "1"
warp = "0.3"
wasmer = "1"